slam_toolbox:
  ros__parameters:
    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: scan
    use_sim_time: true
    
    # SLAM Parameters
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 10.0 
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000
    enable_interactive_mode: false

    # Loop Closure Parameters
    loop_match_minimum_chain_size: 10      
    loop_match_maximum_variance_covariance: 3.0 
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    scan_buffer_size: 10
    
    # Solver Parameters
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None
    
    # Debug
    debug_logging: false
    throttle_scans: 1
    
    # Others
    solve_every_n_laser_scans: 1 
    solve_every_n_meters: 0.5
    mode: mapping 